version: '3.9'
services:
  db:
    image: mysql:latest
    restart: always
    environment:
      - MYSQL_DATABASE=VA_TEST
      - MYSQL_ROOT_PASSWORD=admin_123
    ports:
      - '3306:3306'
  redis-server:
    restart: always
    image: redis:latest
    container_name: test-redis
    ports:
      - "6379:6379"
    volumes:
      - ./redis:/data
volumes:
    redis:
      driver: local
